### ISSUE TITLE
Setup.py incompatible with Wagtail 1.13

### ISSUE THREAD

**Issue by chosak** [cfpb/teachers-digital-platform#167]
This project's [setup.py](https://github.com/cfpb/teachers-digital-platform/blob/d5bc7123a31102f2e05832cb4e37aa0489acb93a/setup.py) file specifies `wagtail>=1.8,<1.11`, which is incompatible with Wagtail 1.13 now used in [cfgov-refresh](https://github.com/cfpb/cfgov-refresh) as of [cfgov-refresh#3841](https://github.com/cfpb/cfgov-refresh/pull/3841).

This means that if you `pip install` this package into an environment with cfgov-refresh dependencies already installed, it will uninstall Wagtail 1.13 and install Wagtail 1.10.

## Steps to replicate behavior (include URLs)

1. Clone [cfgov-refresh](https://github.com/cfpb/cfgov-refresh).
2. `mkvirtualenv --no-site-packages --python=python2.7 cfgov-refresh`
3. `pip install -r requirements/base.txt`
4. `pip install -r requirements/optional-public.txt`

After step 3, Wagtail 1.13 is installed because of cfgov-refresh [requirements](https://github.com/cfpb/cfgov-refresh/blob/master/requirements/wagtail.txt#L1). After step 4, it gets uninstalled and replaced with Wagtail 1.10 because of this project's setup.py.

**Comment by Scotchester** [comment]
Does this project need `wagtail` in its `install_requires` at all?

**Comment by chosak** [comment]
@Scotchester yes; if, ideally, you want to be able to just `pip install` this package and have it pull in its dependencies without needing some other install step. Doing it that way also makes the current [tox.ini](https://github.com/cfpb/teachers-digital-platform/blob/master/tox.ini#L6) work because then you don't have to manually install Wagtail there for testing.

**Comment by Scotchester** [comment]
Wagtail is not a dependency of this project.

**Comment by chosak** [comment]
@Scotchester my mistake then! Then, yes, it should be removed from setup.py completely if it's not required at all.
