### ISSUE TITLE
Linter tests fail and aren't run on Travis

### ISSUE THREAD

**Issue by chosak** [cfpb/teachers-digital-platform#235]
The linter tests `tox -e lint` currently fail. These [don't seem to get run on Travis](https://travis-ci.org/cfpb/teachers-digital-platform/builds/414665640?utm_source=github_status&utm_medium=notification), maybe because of this repo's use of [tox-travis](https://github.com/cfpb/teachers-digital-platform/blob/master/.travis.yml#L6) only runs the Python 2.7/3.6 tox environments.

## Current behavior

Linter tests fail and aren't run automatically on pull requests.

## Expected behavior

Linter tests pass and are run automatically on pull requests, and block PRs if they fail.

## Steps to replicate behavior (include URLs)

1. `tox -e lint`

Review the [recent Travis builds](https://travis-ci.org/cfpb/teachers-digital-platform/builds/419252191) and you'll see the logs don't include running the linter.

**Comment by nbucknor** [comment]
Hi @chosak, I just noticed this issue. Is this something that I'll need to address or is it in your queue?

**Comment by chosak** [comment]
Hi @nbucknor, if you could address it that would be wonderful. It'd be great to have the linter tests running automatically.

**Comment by chosak** [comment]
Thanks @nbucknor!
