### ISSUE TITLE
Searching for terms that include unicode characters result in 500 errors, weird page embed

### ISSUE THREAD

**Issue by Scotchester** [cfpb/teachers-digital-platform#261]
## Current behavior

Searching for terms that include unicode characters result in 500 errors, and bizarrely, a full error page gets _embedded inside_ the search interface.

## Expected behavior

- Searches would complete successfully
- Even if an error occurred, it would display more gracefully

## Steps to replicate behavior (include URLs)

1. Enter a unicode character, e.g., `ë` in the search field and hit Enter or click Search
1. See a full 500 error page appear within the area reserved for the search interface:

![image](https://user-images.githubusercontent.com/1044670/45571359-f058e280-b833-11e8-8d2e-a175ddea87e0.png)

Can also just get the straight-up error page by going to a URL directly with such a character in the query string: https://beta.consumerfinance.gov/practitioner-resources/youth-financial-education/teach/activities/?q=%C3%AB

**Comment by nbucknor** [comment]
@Scotchester This is resolved in #263

**Comment by stephanieosan** [comment]
I can verify this returns a no results screen instead of a 500 error. 
<img width="1142" alt="screen shot 2018-09-17 at 3 28 14 pm" src="https://user-images.githubusercontent.com/6433178/45645386-40cb7c80-ba8e-11e8-8b40-e3ff3efe1edf.png">
