### ISSUE TITLE
Saving the CR tool's results fails in Firefox

### ISSUE THREAD

**Issue by higs4281** [cfpb/teachers-digital-platform#264]
The CR tool's save-to-PDF routine works in Chrome, but in Firefox only the first page is captured.  
Since the data are stored in the browser, a user could lose a rather lengthy review, thinking it had been saved as PDF, only to find it's mostly gone.

**Comment by atuggle** [comment]
Adding @dcmouyard to this issue, as it might be a CSS issue (maybe?)
* https://support.mozilla.org/en-US/questions/1198054

**Comment by dcmouyard** [comment]
The problem turns out to be `display: inline-block` on `.content_main` which is coming from the grid system in capital-framework.

Checking with the BCFP devs to see what’s the best path forward.

**Comment by dcmouyard** [comment]
After chatting with Scott, I’m just going to fix the issue for the CR tool print pages. An issue to fix this site-wide will be added to the CFGOV/platform repo.

**Comment by stephanieosan** [comment]
Fix is here: https://github.com/cfpb/teachers-digital-platform/pull/283

**Comment by Scotchester** [comment]
Deployed.
