### ISSUE TITLE
Search page doesn't handle server errors gracefully

### ISSUE THREAD

**Issue by chosak** [cfpb/teachers-digital-platform#270]
Issue #261 described how a server error on the search page could result in a nested 500 page appearing in the search results area. This was fixed on the backend in #263, but the general problem still remains: if the search endpoint fails somehow, the error isn't handled and the 500 page gets embedded.

See the search JS code [here](https://github.com/cfpb/teachers-digital-platform/blob/master/teachers_digital_platform/js/search.js#L99) and [here](https://github.com/cfpb/teachers-digital-platform/blob/master/teachers_digital_platform/js/search.js#L162). This code takes the response from the search query and sticks it into the page without verifying that the response code is 200. If something other than 200, an error message should be displayed instead.

(Aside: it'd be nice if this retrieval/display code was combined instead of duplicated.)

## Current behavior

Server errors (500s) result in embedded error page as displayed in #261.

## Expected behavior

Error message displayed to the user or other graceful handling.

## Steps to replicate behavior (include URLs)

This is a little hard to replicate without being about to reliably trigger a server error. We can't guarantee there'll never be a server error on the backend; for example, Elasticsearch could fail or there could be some other unexpected problem.

One way to reproduce this is to run your Django server locally, access the search page, then stop your database service (to simulate the DB going down). Then try entering a query on the search page, and you'll see the error:

![image](https://user-images.githubusercontent.com/654645/45697284-6c547280-bb33-11e8-9162-7d0ddb9697ae.png)

**Comment by nbucknor** [comment]
@chosak I've updated the javascript to use the same error handling as eRegs [here](https://github.com/cfpb/teachers-digital-platform/blob/master/teachers_digital_platform/js/search.js#L136). I also combined the code like you requested.

**Comment by chosak** [comment]
Thanks @nbucknor! I can confirm that this error no longer appears. Thanks also for the code cleanup.

It would be nice if there was some kind of message displayed to the user when this happens, but I've seen you've added a TODO [here](https://github.com/cfpb/teachers-digital-platform/blob/ff92fc946bef555dfcb70e76403e9cd9399ea0da/teachers_digital_platform/js/search.js#L148).
